# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  aspnetcoreapi:
    image: aspnetcoreapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5055:5055
      - 7088:7088
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
